server:
  port: 8666
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: lottery
spring:
  datasource:
    url: jdbc:mysql://10.226.133.35:3002/jcloud_record?useUnicode=true&characterEncoding=utf8
    username: root
    password: qweRTs45*hj
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      maximum-pool-size: 5
  mvc:
    view:
      suffix: .html
      cache: false
      prefix: /
  resources:
    static-locations: classpath:web/
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath*:mapper/*.xml
